databases:
  - name: recipeappdb
    databaseName: databaseforrecipeapp
    user: userdb

services:
  - type: web
    name: recipeapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipeappdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
